---
title: "MMOI_Lab3"
output: html_document
date: "2022-10-26"
---

Loading libraries

```{r}
library(GGally)
library(corrr)
```

Діаграма розсіювання

```{r}
df<-read.csv("dataset_3.csv", stringsAsFactors = TRUE)
ggpairs(df[,c(5, 7)])
```

Регресійна модель

```{r}
model<-lm(df[,c(5)]~df[,c(7)])
model
summary(model)
```

Лінія регресії + діаграма розсіювання

```{r}
plot(df[,c(5, 7)])
abline(model, col = "blue")
```

Відгук-прогноз

```{r}
plot(df[,c(5)] ~ fitted(model), xlab = "Прогнозовані моделлю значення", ylab = "Значення спостережень", main = "Діаграма \"відгук-прогноз\" ")
abline(0, 1)
```

Прогноз-залишки

```{r}
plot(resid(model) ~ fitted(model), xlab = "Прогнозовані моделлю значення", ylab = "Залишки моделі", main = "Діаграма \"прогноз-залишки\" ")
abline(h = 0)
```

QQ-plot

```{r}
qqnorm(resid(model), main = "Q-Q-діаграма для залишків моделі", xlab = "Теоретичні квантилі", ylab = "Емпіричні квантилі")
qqline(resid(model))
```

Діаграма залишків за номером спостереження

```{r}
plot(c(1:length(df[,c(5)])), resid(model), xlab = "Порядковий номер", ylab = "Значення залишків", main = "Значення залишків за порядковим номером")
abline(h = 0)
```