---
title: "Lab5"
output: html_document
date: "2022-11-16"
---

```{r}
library(ggplot2)
library(astsa)
library(forecast)
library(TTR)
library(MLmetrics)
library(tseries)
df<-read.csv("Rainfall_1901_1975_PAK.csv", stringsAsFactors = TRUE)
data = ts(df$Rainfall, df$Year, frequency = 12, start = c(1901, 1), end = c(1975, 12))
```

```{r}
plot(data, xlab = 'Year', ylab = 'Rainfall')
ggseasonplot(data, polar = T)
ggseasonplot(data)
```

```{r}
plot.ts(SMA(data, n=5))
plot.ts(SMA(data, n=10))
plot.ts(SMA(data, n=20))
plot.ts(SMA(data, n=50))
plot.ts(SMA(data, n=100))
```

```{r}
DecDATA <- decompose(data)
plot(DecDATA)
```

```{r}
acf(data)
pacf(data)
```

```{r}
ar(data, order.max = 4)
```

```{r}
data.1 <- meanf(data, h=12)
data.2 <- rwf(data, h=12)
data.3 <- snaive(data, h=12)
data.4 <- rwf(data, drift = TRUE, h=12)
autoplot(window(data, start=1951)) +
  autolayer(data.1, series="Mean", PI=FALSE) +
  autolayer(data.2, series="Naïve", PI=FALSE) +
  autolayer(data.3, series="Seasonal naïve", PI=FALSE) +
  autolayer(data.4, series="Drift method", PI=FALSE) +
  xlab("Years") + ylab("Rainfall") +
  ggtitle(" ")
```

```{r}
train.Rainfall <- window(data, start = c(1901, 1), end = c(1965, 12))
valid.Rainfall <- window(data, start = c(1966, 1))
Rainfall.naive <- snaive(train.Rainfall, h = length(valid.Rainfall))
```

```{r}
plot(data, col="blue", xlab="Year", ylab="Rainfall", main="Seasonal Naive Forecast", type='l')
lines(Rainfall.naive$mean, col="red", lwd=2)
```

```{r}
data.HW <- HoltWinters(data)
data.HW.diff <- HoltWinters(data)
data.forecast<-forecast(data.HW)
data.forecast.diff<-forecast(data.HW.diff)
plot(data.forecast)
```

```{r}
plot(data.forecast.diff, xlim=c(1966, 1975))
```

```{r}
res.HW.data <- residuals(data.HW.diff)
checkresiduals(res.HW.data)
```

```{r}
adf.test(data)
```

```{r}
ARIMA.data <- auto.arima(data)
autoplot(forecast(ARIMA.data), level = c(95), h = 50)
```

```{r}
res.Arima.data <- residuals(ARIMA.data)
checkresiduals(res.Arima.data)
```